/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.awt.Dimension;

import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setMinimumSize(new Dimension(1000, 1000));
    }
}
